const products = [
    {
        id: 0, 
        name: "CommonTech G230 Super Pro",
        price: 100, 
        instock: 100,
        imgSrc: "images/peripherals-item-1.png",
    },
    {
        id: 1,
        name: "Shaver Naga v2 Pro",
        price: 100,
        instock: 100,
        imgSrc: "images/peripherals-item-2.png",
    },
    {
        id: 2,
        name: "Shaver Uwabami tenkeyless V3 Lite(Clicky)",
        price: 100,
        instock: 100,
        imgSrc: "images/peripherals-item-3.png",
    },
    {
        id: 3,
        name: "Shaver BlackHunter Pro 65%",
        price: 100,
        instock: 100,
        imgSrc: "images/peripherals-item-4.png",
    },
    {
        id: 4,
        name: "ElementOne Hydrogen 24HFI 24″ / 1080P / 75Hz / 1ms / IPS",
        price: 100,
        instock: 100,
        imgSrc: "images/monitor-item-1.png",
    },
    {
        id: 5,
        name: "ElementOne Mercury 27HGCV 27″ / 1080p / 240hZ / 1ms / VA Curved",
        price: 100,
        instock: 100,
        imgSrc: "images/monitor-item-2.png",
    },
    {
        id: 6,
        name: "ElementOne Mercury 34HGCV 34″ / UW / 1440P / 144Hz / 1ms / VA Curved",
        price: 100,
        instock: 100,
        imgSrc: "images/monitor-item-3.png",
    },
    {
        id: 6,
        name: "GAM 284FHUE ULTRA",
        price: 100,
        instock: 100,
        imgSrc: "images/monitor-item-4.png",
    },
]